name: hugo-modules-caching

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Check Hugo Modules Caching
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.123.7'
          extended: true

      - name: Print Hugo cache directory
        run: hugo config | grep cachedir

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: /home/runner/.cache/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        working-directory: ${{ inputs.name }}
        run: |
          hugo --minify --gc
